export const error = {
    INTERNAL_SERVER_ERROR: "Internal server error",
    USER_NOT_FOUND:  "User not found",
    USER_BLOCKED:  "User blocked",
    INVALID_CREDENTIALS: "Invalid credentials",
    EMAIL_NOT_VERIFIED:  "Email not verified",
    INCORRECT_PASSWORD: "Password must be a valid password",
    ACTIVE_SESSION_EXISTS: "There is an active session",
    INVALID_AUTHORIZATION_HEADER: "Unauthorized - Invalid Authorization header",
    INVALID_TOKEN_HEADER: "Unauthorized - Invalid token",
    VERIFICATION_CODE_NOT_FOUND: "Verification code not found",
    VERIFICATION_CODE_EXCEEDED_ATTEMPTS_LIMIT: "Verification code entry limit reached, please try sending the code again",
    VERIFICATION_CODE_MISMATCH: "Verification code does not match",
    VERIFICATION_CODE_EXPIRED: "Verification code is expired",
    REQUEST_LIMIT_EXHAUSTED: "Request limit exhausted",
    FORBIDDEN: "Access is denied",
    VERIFICATION_CODE_LIMIT_REACHED: "Daily verification code limit reached",
    CANNOT_CHAT_WITH_SELF: "You can't create a chat with yourself",
    NOT_ENOUGH_USERS: "Group chat must have at least 2 members",
    CHAT_NOT_FOUND: "The chat does not exist",
    CHAT_ALREADY_DELETED: "Chat has already been deleted",
    CHAT_ARCHIVED: "The chat is already archived",
}